### ISSUE TITLE
Plugin doesn't seem to be working for me at all, at least, based on my expectations from the description.

### ISSUE THREAD

**Issue by tallship** [hackernoon/Free-Internet-Plugin#15]
**Plugin appears to not be working at all**

Based on the description in the email received and the freeinternetplugin.com website, as well as the article on HackerNoon, the plugin doesn't appear to be working as described... at all really.

***Browser***  |  ***Search Engine***
Vivaldi (latest)   |    StartPage.com

Brave (latest)     |   DuckDuckGo

**To Reproduce**

* install either Vivaldi or Brave Browser
* Configure either StartPage or DuckDuckGo as the search engine of choice.
* Use Search Term: "<name of blocked paywalled site> about"
i.e., new york times about or wall street journal about

**Expected behavior**

* Expected behavior is that the user will not see links to the paywalled sites in the SERPs.

**Desktop (please complete the following information):**
 - OS: Win10/64, Slackware -current, Debian Bulseye, Arch Linux
 - Browser: Vivaldi 4.0.2312.27 (Stable channel) (64-bit)
 - Browser: Brave Version 1.25.73 Chromium: 91.0.4472.106 (Official Build) (64-bit)

*Actual Behavior*

* Search returns show multiple links to the actual sites that have blocking enabled in the plugin's config. i.e., NYT/WSJ, etc.
* Paywalled sites, if visited via the links returned in search results will, as intended by those website publishers, throw up a paywall after a few seconds or after attempting to scroll the article in order to read.
* It is as if the plugin does not work at all, and indeed, seems as if it does not. 

**Smartphone (please complete the following information):**
 - Device: Have yet to test (Might be pointless)
 - OS: Android and CalyxOS
 - Browser: Vivaldi and Brave
 - Version: Will be the latest if plugin is installed and tested.

**Additional Details**

I wanted to leave a glowing review for the plugin in the chrome store. both browsers are compatible with Chrome plugins and there are currently only seven reviews. After an initial check to make sure that the plugin works it seems to absolutely not work at all, browser restarts, system reboot on windows, etc., fail to affect the behavior of search returns from DDG and StartPage. The same behavior is exhibited when using the Gigablast search engine.

I have not, nor will, test with Google as the search engine, so if this plugin only works with results from Google.com as the search provider then I would think that should be stated and then people who will never use Google will know this plugin is not for them.

I didn't want to just leave a review stating that the plugin doesn't work for me at all considering that the existing 6 reviewers awarded five stars each, so I figure there must be something in the configs (I changed/altered nothing) that needs to be set in order for this plugin to work as advertised.

**Comment by Torbet** [comment]
Hi Bradley, thank you for getting in contact!

Currently, the users browser should not inhibit the plugin, but the plugin only works for Google search results, as they hold 92% of users and each search engine would require a custom script to work effectively.

Thank you for writing, I'm sorry that we can't meet your needs at this time.

**Comment by tallship** [comment]
Hi @Torbet , Okay I checked using Google.com and indeed, I can atest that I did not see any "nytimes.com" or similar for wsj, etc. - basically anything on the block list. nytco.com did come up, but that's not actually a paywalled site so it doesn't count ;)

Then I disabled the plugin, hit refresh, and voila! lotsa paywall crapolla down the page!

So.... I find it rather unfortunate that, as you state, that the plugin only works for results from searching via Google.com proper, as that's not a site that I typically will frequent, and sadly, they're going to get those paywalled results to me anyway via StartPage, since it's an aggregation of Google data.

Good news is... the plugin works as stated, quite well, and  without any noticeable degradation in time to retrieve results, but due to a myriad of reasons why I and others will not use Google.com for search results, the plugin isn't going to benefit me much, or at least very often, at this time.

Given some time, contributory PRs, and perhaps a bit of funding from folks, perhaps you'll be able to expand upon the list of actual search engines that this plugin serves, since it does indeed to do what it sets out to do so well. For that, I am quite elated!

I'm not going to close this issue however, since I would imagine that many others who remove Google as their search provider from their browsers will come across the same confusion, but please do feel free to close the issue if you feel it best :)

If you're open to it, I made two clarifications in the text and issued a PR for you to consider. With that, #16 , this issue probably won't serve a purpose any longer :)

Thanks for this fantastic plugin - a sorely needed takeback for privacy concsious individuals!

**Comment by Torbet** [comment]
Thank you for the feedback, will look over your PR and update the readme to make everything more transparent!
It is still early days and we wanted to get a MVP out the door, which I think you can agree targeting Google results is the best option to start with. With time, we will definitely look into supporting more search engines and then can hopefully cater to the more privacy-oriented folks!
